CREATE OR REPLACE TRIGGER HISTORIAL_SUELDOS
AFTER UPDATE OF SALARIO ON EMPLEADOS
FOR EACH ROW 
WHEN (OLD.SALARIO <> NEW.SALARIO)
BEGIN 
REGISTRAR_SALARIO (:OLD.EMPLEADO_ID,:NEW.SALARIO,SYSDATE);
END;
/