CREATE PROCEDURE REGISTRAR_SALARIO(

    V_EMPLEADO_ID HISTORIAL_SUELDOS.EMPLEADO_ID%TYPE,
    V_SALARIO HISTORIAL_SUELDOS.SALARIO%TYPE,
    V_FECHA HISTORIAL_SUELDOS.FECHA%TYPE
)
IS
BEGIN
INSERT INTO HISTORIAL_SUELDOS(FECHA,EMPLEADO_ID,SALARIO) VALUES(V_FECHA,V_EMPLEADO_ID,V_SALARIO);
END REGISTRAR_SALARIO;
/




CREATE OR REPLACE TRIGGER HISTORIAL_SUELDOS
AFTER UPDATE OF SALARIO ON EMPLEADOS
FOR EACH ROW 
WHEN (OLD.SALARIO <> NEW.SALARIO)
BEGIN 
REGISTRAR_SALARIO (:OLD.EMPLEADO_ID,:NEW.SALARIO,SYSDATE);
END;
/