------ CREACION DE TABLAS ---------
CREATE TABLE HISTORIAL_SUELDOS(
    FECHA DATE,
    EMPLEADO_ID NUMBER(6),
    SALARIO NUMBER(8,2)
);
COMMENT ON TABLE HISTORIAL_SUELDOS IS 'TABLA PARA REGISTRAR LOS CAMBIOS EN LOS SUELDOS';
COMMENT ON COLUMN HISTORIAL_SUELDOS.FECHA  IS 'FECHA EN LA QUE RECIBIO UN NUEVO SUELDO';
COMMENT ON COLUMN HISTORIAL_SUELDOS.EMPLEADO_ID  IS 'ID DEL EMPLEADO CON NUEVO SUELDO';
COMMENT ON COLUMN HISTORIAL_SUELDOS.SALARIO  IS 'NUEVO SALARIO REGISTRADO';

CREATE TABLE  PAISES (
  PAIS_ID CHAR(2),
  PAIS_NOMBRE VARCHAR2(40),
  REGION_ID NUMBER
);
COMMENT ON TABLE PAISES IS 'PAISES DONDE TRABAJA LA EMPRESA';
COMMENT ON COLUMN PAISES.PAIS_NOMBRE IS 'NOMBRE DEL PAIS';
COMMENT ON COLUMN PAISES.REGION_ID IS 'LLAVE FORANEA DE LA REGION';

CREATE TABLE DEPARTAMENTOS(
  DEPARTAMENTO_ID NUMBER(4),
  DEPARTAMENTO_NOMBRE VARCHAR2(30),
  GERENTE_ID NUMBER(6),
  LOCALIZACION_ID NUMBER(4)
);
COMMENT ON TABLE DEPARTAMENTOS IS 'TABLA PARA GUARDAR LOS DEPARTAMENTOS';
COMMENT ON COLUMN DEPARTAMENTOS.DEPARTAMENTO_NOMBRE IS 'NOMBRE DEL DEPARTAMENTO';
COMMENT ON COLUMN DEPARTAMENTOS.GERENTE_ID IS 'ID DEL EMPLEADO QUE ES GERENTE';
COMMENT ON COLUMN DEPARTAMENTOS.LOCALIZACION_ID IS 'LLAVE FORANEA DE LA LOCALIZACION';

CREATE TABLE EMPLEADOS(
  EMPLEADO_ID NUMBER(6),
  PRIMER_NOMBRE VARCHAR2(20),
  APELLIDO VARCHAR2(25),
  CORREO VARCHAR2(25),
  NUMERO_TELEFONO VARCHAR2(20),
  FECHA_CONTRATO DATE,
  CARGO_ID VARCHAR2(10),
  SALARIO NUMBER(8,2),
  COMISION_PCT NUMBER(2,2),
  GERENTE_ID NUMBER(6),
  DEPARTAMENTO_ID NUMBER(4)
);

COMMENT ON  TABLE EMPLEADOS IS 'TABLA PARA GUARDAR EMPLEADOS';
COMMENT ON  COLUMN  EMPLEADOS.APELLIDO IS 'APELLIDO DEL EMPLEADO';
COMMENT ON  COLUMN EMPLEADOS.CARGO_ID IS 'LLAVE FORANEA DEL CARGO REFERENCIADA EN CARGOS';
COMMENT ON COLUMN EMPLEADOS.COMISION_PCT IS 'COMISION DE LOS EMPLEADOS EN PORCENTAJE';
COMMENT ON COLUMN EMPLEADOS.CORREO IS 'CORREO UNICO DE CADA EMPLEADO';
COMMENT ON COLUMN EMPLEADOS.DEPARTAMENTO_ID IS 'FORANEA QUE REFERENCIA AL ID DEL DEPARTAMENTO';
COMMENT ON COLUMN EMPLEADOS.FECHA_CONTRATO IS 'FECHA DEL CONTRATO ACTUAL';
COMMENT ON COLUMN EMPLEADOS.GERENTE_ID IS 'LLAVE FORANEA DEL ID DE OTRO EMPLEADO';
COMMENT ON COLUMN EMPLEADOS.EMPLEADO_ID IS 'NUMERO DE ID DEL EMPLEADO';
COMMENT ON COLUMN EMPLEADOS.PRIMER_NOMBRE IS 'PRIMER NOMBRE DEL EMPLEADO';
COMMENT ON COLUMN EMPLEADOS.NUMERO_TELEFONO IS 'NUMERO DE TELEFONO DEL EMPLEADO';


CREATE TABLE HISTORIAL_CARGOS(
  EMPLEADO_ID NUMBER(6),
  FECHA_INICIO DATE,
  FECHA_FIN DATE,
  CARGO_ID VARCHAR2(10),
  DEPARTAMENTO_ID NUMBER(4)
);

COMMENT ON TABLE  HISTORIAL_CARGOS IS 'TABLA PARA EL HISTORIAL DE LOS CARGOS DE LOS EMPLEADOS';
COMMENT ON COLUMN HISTORIAL_CARGOS.EMPLEADO_ID IS 'ID DEL EMPLEADO';

CREATE TABLE CARGOS(
  CARGO_ID VARCHAR2(10),
  CARGO_TITULO VARCHAR2(35),
  SALARIO_MIN NUMBER(6),
  SALARIO_MAX NUMBER(6)
);

CREATE TABLE LOCALIZACIONES(
  LOCALIZACION_ID NUMBER(4),
  DIRECCION_CALLE VARCHAR2(40),
  CODIGO_POSTAL VARCHAR2(12),
  CIUDAD VARCHAR2(30),
  ESTADO_PROVINCIA VARCHAR2(25),
  PAIS_ID CHAR(2)
);

CREATE TABLE REGIONES(
  REGION_ID NUMBER,
  REGION_NOMBRE VARCHAR2(25)
);

---------------------------

SELECT *FROM EMPLEADOS