------ CREACION DE TABLAS ---------
CREATE TABLE HISTORIAL_SUELDOS(
    FECHA DATE,
    EMPLEADO_ID NUMBER(6),
    SALARIO NUMBER(8,2)
);
CREATE TABLE  PAISES (
  PAIS_ID CHAR(2),
  PAIS_NOMBRE VARCHAR2(40),
  REGION_ID NUMBER
);

CREATE TABLE DEPARTAMENTOS(
  DEPARTAMENTO_ID NUMBER(4),
  DEPARTAMENTO_NOMBRE VARCHAR2(30),
  GERENTE_ID NUMBER(6),
  LOCALIZACION_ID NUMBER(4)
);

CREATE TABLE EMPLEADOS(
  EMPLEADO_ID NUMBER(6),
  PRIMER_NOMBRE VARCHAR2(20),
  APELLIDO VARCHAR2(25),
  CORREO VARCHAR2(25),
  NUMERO_TELEFONO VARCHAR2(20),
  FECHA_CONTRATO DATE,
  CARGO_ID VARCHAR2(10),
  SALARIO NUMBER(8,2),
  COMISION_PCT NUMBER(2,2),
  GERENTE_ID NUMBER(6),
  DEPARTAMENTO_ID NUMBER(4)
);

CREATE TABLE HISTORIAL_CARGOS(
  EMPLEADO_ID NUMBER(6),
  FECHA_INICIO DATE,
  FECHA_FIN DATE,
  CARGO_ID VARCHAR2(10),
  DEPARTAMENTO_ID NUMBER(4)
);

CREATE TABLE CARGOS(
  CARGO_ID VARCHAR2(10),
  CARGO_TITULO VARCHAR2(35),
  SALARIO_MIN NUMBER(6),
  SALARIO_MAX NUMBER(6)
);

CREATE TABLE LOCALIZACIONES(
  LOCALIZACION_ID NUMBER(4),
  DIRECCION_CALLE VARCHAR2(40),
  CODIGO_POSTAL VARCHAR2(12),
  CIUDAD VARCHAR2(30),
  ESTADO_PROVINCIA VARCHAR2(25),
  PAIS_ID CHAR(2)
);

CREATE TABLE REGIONES(
  REGION_ID NUMBER,
  REGION_NOMBRE VARCHAR2(25)
);

//---------------------------


