SELECT 'DROP TABLE '||table_name||' CASCADE CONSTRAINTS;' FROM user_tables;

DROP TABLE DEPARTAMENTOS CASCADE CONSTRAINTS;
DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
DROP TABLE HISTORIAL_CARGOS CASCADE CONSTRAINTS;
DROP TABLE CARGOS CASCADE CONSTRAINTS;
DROP TABLE LOCALIZACIONES CASCADE CONSTRAINTS;
DROP TABLE REGIONES CASCADE CONSTRAINTS;
DROP TABLE PAISES CASCADE CONSTRAINTS;
DROP TABLE HISTORIAL_SUELDOS CASCADE CONSTRAINTS;