--LLAVES PRIMARIAS
ALTER TABLE PAISES ADD CONSTRAINT
  PAIS_PK PRIMARY KEY (PAIS_ID); --BIEN

ALTER TABLE REGIONES ADD CONSTRAINT
  REG_ID_PK PRIMARY KEY (REGION_ID);--BIEN

ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT
  DEPARTAMENTOS_ID_PK PRIMARY KEY (DEPARTAMENTO_ID); --BIEN

ALTER TABLE EMPLEADOS ADD CONSTRAINT
  EMPLEADO_ID_PK PRIMARY KEY (EMPLEADO_ID);--BIEN

ALTER TABLE CARGOS ADD CONSTRAINT
  CARGO_ID PRIMARY KEY (CARGO_ID);--BIEN

ALTER TABLE LOCALIZACIONES ADD CONSTRAINT
  LOC_ID_PK PRIMARY KEY (LOCALIZACION_ID);--BIEN

ALTER TABLE HISTORIAL_CARGOS ADD CONSTRAINT
  HISTCAR_EMP_ID_INI_FCH_PK PRIMARY KEY (EMPLEADO_ID,FECHA_INICIO);--BIEN

--LLAVES FORANEAS

ALTER TABLE PAISES ADD CONSTRAINT
  PAIS_REG_FK FOREIGN KEY (REGION_ID) REFERENCES  REGIONES(REGION_ID);--BIEN



ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT
  DEPARTAMENTOS_LOC_FK FOREIGN KEY (LOCALIZACION_ID) REFERENCES  LOCALIZACIONES(LOCALIZACION_ID);--BIEN
/*ALTER TABLE  DEPARTAMENTOS ADD CONSTRAINT
  DEPARTAMENTOS_GRT_ID FOREIGN KEY (GERENTE_ID) REFERENCES EMPLEADOS(EMPLEADO_ID);--BIEN*/


ALTER TABLE EMPLEADOS ADD CONSTRAINT
  EMP_CORREO_UK UNIQUE (CORREO);--BIEN
ALTER TABLE EMPLEADOS ADD CONSTRAINT
  EMP_DEPARTAMENTOS_FK FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES  DEPARTAMENTOS(DEPARTAMENTO_ID);--BIEN
ALTER TABLE EMPLEADOS ADD CONSTRAINT
  EMP_CARGO_FK FOREIGN KEY (CARGO_ID) REFERENCES  CARGOS(CARGO_ID);--BIEN
ALTER TABLE EMPLEADOS ADD CONSTRAINT
  EMP_GERENTE_FK FOREIGN KEY (GERENTE_ID) REFERENCES  EMPLEADOS(EMPLEADO_ID);--BIEN


ALTER TABLE HISTORIAL_CARGOS ADD CONSTRAINT
  HISTCAR_DEP_FK FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTOS(DEPARTAMENTO_ID);--BIEN
ALTER TABLE HISTORIAL_CARGOS ADD CONSTRAINT
  HISTCAR_EMP_FK FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADOS(EMPLEADO_ID);--BIEN
ALTER TABLE HISTORIAL_CARGOS ADD CONSTRAINT
  HISTCAR_CARGO_FK FOREIGN KEY (CARGO_ID) REFERENCES CARGOS(CARGO_ID);--BIEN


ALTER TABLE LOCALIZACIONES ADD CONSTRAINT
  LOC_PAIS_ID_FK FOREIGN KEY (PAIS_ID) REFERENCES  PAISES(PAIS_ID);--BIEN




